### ISSUE TITLE
Durable Projections

### ISSUE THREAD

**Issue by woodpk** [AfterLutz/Akkatecture#112]
I know that durable projections was something in the roadmap before everything was moved to /AfterLutz and it would be nice to see this on a roadmap now.

**Comment by malclear** [comment]
I totally agree that resumable projections should be part of the library, or as an add-on. I was thinking about this, coincidentally, when you opened this ticket.
We also need a clearly-stated roadmap. I think I might start with a Discussion first; I'd appreciate your input on the topic there.

**Comment by malclear** [comment]
Please see the discussion here: https://github.com/AfterLutz/Akkatecture/discussions/33
