### ISSUE TITLE
NuGet: need to rename all packages

### ISSUE THREAD

**Issue by Aaronontheweb** [AfterLutz/Akkatecture#48]
In order to be published on NuGet we need to rename all of the Akkatecture NuGet packages.

I configured our NuGet publish key to look for `AfterLutz.*` paths, so that might be the easiest solution: just prepend `AfterLutz.` to the front of each project name.

Related: https://github.com/AfterLutz/Akkatecture/issues/34#issuecomment-1004847924

**Comment by malclear** [comment]
This approach was changed so that there would be an "AL" suffix added to the original package names. Examples include: `Akkatecture.AL` and `Akkatecture.Clustering.AL`.
