### ISSUE TITLE
Test has invalid name

### ISSUE THREAD

**Issue by malclear** [AfterLutz/Akkatecture#73]
The test linked below has a name ending with "throws exception". It should end with "succeeds"

https://github.com/AfterLutz/Akkatecture/blob/1a846b4b830f36ac20e03753b197924803892e79/test/Akkatecture.Tests/UnitTests/Commands/CommandTests.cs#L13

**Comment by Aman-Mandal** [comment]
Hey can I work on this?

**Comment by malclear** [comment]
Aman,
Yes! Thank you for offering. You can find instructions for opening a PR in
the Readme of the Akkatecture project.

*Malcolm Learner*
